name: Docker

on:
  push:
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

env:
  IMAGE_NAME: consul-ecs

jobs:
  push:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          CONSUL_VERSION=$(echo ${VERSION} | cut -d- -f1 | sed -e 's/^v//')
          ENVOY_VERSION=$(echo ${VERSION} | cut -d- -f2 | sed -e 's/^v//')
          
          docker build . --file Dockerfile --tag $IMAGE_NAME --build-arg CONSUL_VERSION=${CONSUL_VERSION} --build-arg ENVOY_VERSION=${ENVOY_VERSION}

      - name: Log into Docker Hub
        run: echo "${{ secrets.CR_PAT }}" | docker login -u ${{ github.actor }} --password-stdin

      - name: Push image to Docker Hub
        run: |
          IMAGE_ID=${{ github.repository_owner }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
